url = https://www.saucedemo.com
browser = chrome
username = standard_user
password = secret_sauce
prdName = Sauce Labs Backpack
firstName=Mariam
lastName=Ramadan
zipCode=123
invalidusername=mariam
invalidpassword=123


